#Models constants

##UserRole
USER_ROLE_NAME_MAX_LENGTH = 50

##AppUser
USERNAME_MAX_LENGTH = 150
USERNAME_MIN_LENGTH = 5
FIRST_NAME_MAX_LENGTH = 150
FIRST_NAME_MIN_LENGTH = 5
LAST_NAME_MAX_LENGTH = 150
LAST_NAME_MIN_LENGTH = 5
EMAIL_MAX_LENGTH = 250
EMAIL_MIN_LENGTH = 5
PASSWORD_MAX_LENGTH = 150
PASSWORD_MIN_LENGTH = 5
